import Link from "next/link";
import { Brand } from "@/components/ui";

export const dynamic = "force-dynamic";

export default function NotFound() {
  return (
    <div className="min-h-screen bg-bg text-ink">
      <header className="sticky top-0 z-30 border-b border-line bg-bg/90 backdrop-blur">
        <div className="mx-auto flex max-w-6xl items-center justify-between px-5 py-3.5">
          <Link href="/" className="transition-opacity hover:opacity-85">
            <Brand />
          </Link>
          <span className="font-data hidden text-[11px] uppercase tracking-[0.12em] text-faint sm:block">multi-agent site audit</span>
        </div>
      </header>

      <main className="grid-paper">
        <div className="mx-auto flex max-w-6xl flex-col items-center px-5 pb-24 pt-16 text-center sm:pt-24">
          <div className="font-data text-[12px] uppercase tracking-[0.18em] text-bad">404 · Not found</div>
          <h1 className="font-display mt-4 max-w-2xl text-3xl font-bold leading-[1.15] tracking-tight sm:text-[40px]">
            This report isn&apos;t here.
          </h1>
          <p className="mt-4 max-w-xl text-[15px] leading-relaxed text-mut">
            The audit report you&apos;re looking for doesn&apos;t exist on this instance — it may have been
            generated by an older build, or the link is stale. Every new audit is stored locally and
            stays available, so just run a fresh scan to get a working report.
          </p>
          <div className="mt-8 flex flex-wrap items-center justify-center gap-3">
            <Link
              href="/"
              className="inline-flex items-center justify-center gap-2 rounded-md bg-acc px-4 py-2 text-sm font-bold text-acctext transition-colors hover:bg-accdeep"
            >
              Run a new audit
            </Link>
            <Link
              href="/"
              className="inline-flex items-center justify-center gap-2 rounded-md border border-line2 bg-panel2 px-4 py-2 text-sm text-ink transition-colors hover:border-acc/50 hover:text-acc"
            >
              Back to dashboard
            </Link>
          </div>
        </div>
      </main>
    </div>
  );
}
